### ISSUE TITLE
Fix bug: content attribute charset value, trailing whitespace

### ISSUE THREAD

**Issue by openandclose** [jsdom/html-encoding-sniffer#6]
The following example should return 'ISO-8859-2'
(note the last whitespace before '"').

`<meta http-equiv="Content-Type" content="text/html; charset=iso8859-2 ">`

While html-encoding-sniffer returns 'defaultEncoding',
calling `whatwgEncoding.labelToName` with `l; charset=`.

line 283:
  `let end = string.substring(position + 1).search(/\x09|\x0A|\x0C|\x0D|\x20|;/);`

`end` gets the index of the shortened string.

**Comment by domenic** [comment]
Thank you for finding all these bugs; they're a bit embarrassing, but much appreciated.

Would you be interested in working on pull requests to fix them?

**Comment by openandclose** [comment]
Please review them.
I'm not certain I should open pull requests.

**Comment by domenic** [comment]
Hey, when you edit your comment after initially sending it, that does not send a notification, so all I received in my email was "Please review them. I'm not certain I should open pull requests."

Thanks for doing that work. I will work on turning them into pull requests for you.

**Comment by openandclose** [comment]
@domenic Sorry about the first previous comment (before edit).
It was a bit confusing.
But I thought you would revisit the issues sooner...

Anyway, I am glad my commits were used.
